from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hesapMakinas(object):
    def setupUi(self, hesapMakinas):
        hesapMakinas.setObjectName("hesapMakinas")
        hesapMakinas.resize(432, 376)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/hesapMakinası.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        hesapMakinas.setWindowIcon(icon)
        self.ekran = QtWidgets.QLineEdit(hesapMakinas)
        self.ekran.setGeometry(QtCore.QRect(0, 0, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ekran.setFont(font)
        self.ekran.setClearButtonEnabled(True)
        self.ekran.setObjectName("ekran")
        self.temizle = QtWidgets.QPushButton(hesapMakinas)
        self.temizle.setGeometry(QtCore.QRect(10, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.temizle.setFont(font)
        self.temizle.setObjectName("temizle")
        self.sayi1 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi1.setGeometry(QtCore.QRect(10, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi1.setFont(font)
        self.sayi1.setObjectName("sayi1")
        self.sayi2 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi2.setGeometry(QtCore.QRect(10, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi2.setFont(font)
        self.sayi2.setObjectName("sayi2")
        self.sayi3 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi3.setGeometry(QtCore.QRect(10, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi3.setFont(font)
        self.sayi3.setObjectName("sayi3")
        self.sayi4 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi4.setGeometry(QtCore.QRect(70, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi4.setFont(font)
        self.sayi4.setObjectName("sayi4")
        self.sayi5 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi5.setGeometry(QtCore.QRect(70, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi5.setFont(font)
        self.sayi5.setObjectName("sayi5")
        self.sayi6 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi6.setGeometry(QtCore.QRect(70, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi6.setFont(font)
        self.sayi6.setObjectName("sayi6")
        self.sayi7 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi7.setGeometry(QtCore.QRect(130, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi7.setFont(font)
        self.sayi7.setObjectName("sayi7")
        self.sayi8 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi8.setGeometry(QtCore.QRect(130, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi8.setFont(font)
        self.sayi8.setObjectName("sayi8")
        self.sayi9 = QtWidgets.QPushButton(hesapMakinas)
        self.sayi9.setGeometry(QtCore.QRect(130, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sayi9.setFont(font)
        self.sayi9.setObjectName("sayi9")
        self.sifir = QtWidgets.QPushButton(hesapMakinas)
        self.sifir.setGeometry(QtCore.QRect(130, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sifir.setFont(font)
        self.sifir.setObjectName("sifir")
        self.ciftSifir = QtWidgets.QPushButton(hesapMakinas)
        self.ciftSifir.setGeometry(QtCore.QRect(10, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ciftSifir.setFont(font)
        self.ciftSifir.setObjectName("ciftSifir")
        self.arti = QtWidgets.QPushButton(hesapMakinas)
        self.arti.setGeometry(QtCore.QRect(300, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.arti.setFont(font)
        self.arti.setObjectName("arti")
        self.eksi = QtWidgets.QPushButton(hesapMakinas)
        self.eksi.setGeometry(QtCore.QRect(370, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.eksi.setFont(font)
        self.eksi.setObjectName("eksi")
        self.carpi = QtWidgets.QPushButton(hesapMakinas)
        self.carpi.setGeometry(QtCore.QRect(230, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.carpi.setFont(font)
        self.carpi.setObjectName("carpi")
        self.bolme = QtWidgets.QPushButton(hesapMakinas)
        self.bolme.setGeometry(QtCore.QRect(370, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bolme.setFont(font)
        self.bolme.setObjectName("bolme")
        self.ustlu = QtWidgets.QPushButton(hesapMakinas)
        self.ustlu.setGeometry(QtCore.QRect(300, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ustlu.setFont(font)
        self.ustlu.setObjectName("ustlu")
        self.esittir = QtWidgets.QPushButton(hesapMakinas)
        self.esittir.setGeometry(QtCore.QRect(300, 260, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.esittir.setFont(font)
        self.esittir.setObjectName("esittir")
        self.karekok = QtWidgets.QPushButton(hesapMakinas)
        self.karekok.setGeometry(QtCore.QRect(230, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.karekok.setFont(font)
        self.karekok.setObjectName("karekok")
        self.label = QtWidgets.QLabel(hesapMakinas)
        self.label.setGeometry(QtCore.QRect(280, 330, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(hesapMakinas)
        QtCore.QMetaObject.connectSlotsByName(hesapMakinas)

    def retranslateUi(self, hesapMakinas):
        _translate = QtCore.QCoreApplication.translate
        hesapMakinas.setWindowTitle(_translate("hesapMakinas", "Hesap Makinası"))
        self.temizle.setText(_translate("hesapMakinas", "Clear-Temizle"))
        self.sayi1.setText(_translate("hesapMakinas", "1"))
        self.sayi2.setText(_translate("hesapMakinas", "2"))
        self.sayi3.setText(_translate("hesapMakinas", "3"))
        self.sayi4.setText(_translate("hesapMakinas", "4"))
        self.sayi5.setText(_translate("hesapMakinas", "5"))
        self.sayi6.setText(_translate("hesapMakinas", "6"))
        self.sayi7.setText(_translate("hesapMakinas", "7"))
        self.sayi8.setText(_translate("hesapMakinas", "8"))
        self.sayi9.setText(_translate("hesapMakinas", "9"))
        self.sifir.setText(_translate("hesapMakinas", "0"))
        self.ciftSifir.setText(_translate("hesapMakinas", "00"))
        self.arti.setText(_translate("hesapMakinas", "+"))
        self.eksi.setText(_translate("hesapMakinas", "-"))
        self.carpi.setText(_translate("hesapMakinas", "x"))
        self.bolme.setText(_translate("hesapMakinas", "÷"))
        self.ustlu.setText(_translate("hesapMakinas", "**"))
        self.esittir.setText(_translate("hesapMakinas", "="))
        self.karekok.setText(_translate("hesapMakinas", "√"))
        self.label.setText(_translate("hesapMakinas", "The MonJoR"))

